# Generated by Django 5.2.11 on 2026-02-28 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['contribution_type'], name='core_contri_contrib_2b42e0_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['paid_at'], name='core_contri_paid_at_d4bce5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='core_docume_title_5a80f0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='core_docume_uploade_e13ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='core_event_starts__2e18e3_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['title'], name='core_event_title_ad75b8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='core_event_locatio_5d3252_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='core_group_name_9ccf81_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_at'], name='core_group_created_332669_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_at'], name='core_meetin_schedul_1db628_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['title'], name='core_meetin_title_c46550_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingentry',
            index=models.Index(fields=['status'], name='core_meetin_status_70b497_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingentry',
            index=models.Index(fields=['recorded_at'], name='core_meetin_recorde_743e82_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['full_name'], name='core_member_full_na_d4e41e_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='core_member_email_1c8df0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='core_member_phone_6f90b3_idx'),
        ),
        migrations.AddIndex(
            model_name='organ',
            index=models.Index(fields=['name'], name='core_organ_name_c0f9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['name'], name='core_positi_name_873dda_idx'),
        ),
    ]
