# Generated by Django 5.2.11 on 2026-09-16 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
        ('otp_totp', '0002_auto_20190420_0723'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.totpdevice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
            ],
            options={
                'verbose_name': 'Appareil TOTP',
                'verbose_name_plural': 'Appareils TOTP',
            },
            bases=('otp_totp.totpdevice',),
        ),
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_widgets', models.JSONField(default=list, verbose_name='Widgets activés')),
                ('widget_order', models.JSONField(default=list, verbose_name='Ordre des widgets')),
                ('layout_columns', models.IntegerField(choices=[(1, '1 colonne'), (2, '2 colonnes'), (3, '3 colonnes'), (4, '4 colonnes')], default=3, verbose_name='Nombre de colonnes')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Auto')], default='light', max_length=20, verbose_name='Thème')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de dashboard',
                'verbose_name_plural': 'Préférences de dashboard',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='Notifications in-app')),
                ('notify_groups', models.BooleanField(default=True, verbose_name='Notifications groupes')),
                ('notify_members', models.BooleanField(default=True, verbose_name='Notifications membres')),
                ('notify_meetings', models.BooleanField(default=True, verbose_name='Notifications rencontres')),
                ('notify_contributions', models.BooleanField(default=True, verbose_name='Notifications cotisations')),
                ('notify_system', models.BooleanField(default=True, verbose_name='Notifications système')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='Codes de secours')),
                ('backup_codes_used', models.JSONField(blank=True, default=list, verbose_name='Codes de secours utilisés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence 2FA',
                'verbose_name_plural': 'Préférences 2FA',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Type')),
                ('category', models.CharField(choices=[('group', 'Groupe'), ('member', 'Membre'), ('meeting', 'Rencontre'), ('contribution', 'Cotisation'), ('system', 'Système')], default='system', max_length=20, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('related_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modèle lié')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet lié")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'), models.Index(fields=['category'], name='core_notifi_categor_3fcfd3_idx')],
            },
        ),
    ]
