# Generated by Django 5.2.11 on 2026-09-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_totpdevice_dashboardpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('monthly', 'Mensuelle'), ('annual', 'Annuelle'), ('spontaneous', 'Spontanee'), ('late_fine', 'Amende retard'), ('absence_fine', 'Amende absence'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.member'),
        ),
    ]
