# Generated by Django 5.2.17 on 2026-09-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Especes'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmee'), ('failed', 'Echouee')], default='confirmed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['payment_status'], name='core_contri_payment_7fc1dc_idx'),
        ),
    ]
