# Generated by Django 5.2.17 on 2026-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contribution_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
