# Generated by Django 5.2.17 on 2026-09-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contribution_gateway_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('organization_type', models.CharField(choices=[('company', 'Société'), ('association', 'Association'), ('local_authority', 'Collectivité'), ('club', 'Club / groupe')], max_length=20, verbose_name="Type d'organisation")),
                ('message', models.TextField(verbose_name='Besoin principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
