# Generated by Django 5.2.17 on 2026-09-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_proposalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('monthly', 'Mensuelle'), ('annual', 'Annuelle'), ('spontaneous', 'Spontanée'), ('late_fine', 'Amende retard'), ('absence_fine', 'Amende absence'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('failed', 'Échouée')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingentry',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('permission', 'Permission')], max_length=20),
        ),
    ]
