# Generated by Django 5.2.17 on 2026-09-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_translatable_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='gateway_reference',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Référence du paiement'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payer_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Numéro payeur'),
        ),
    ]
