# Generated by Django 5.2.17 on 2026-09-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contribution_gateway_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name='Nom')),
                ('author_role', models.CharField(blank=True, help_text='Ex. Trésorière', max_length=120, verbose_name='Fonction')),
                ('organization', models.CharField(blank=True, max_length=160, verbose_name='Organisation')),
                ('quote', models.TextField(max_length=600, verbose_name='Témoignage')),
                ('consent_given', models.BooleanField(default=False, help_text='Obligatoire pour publier : le client a accepté que son avis et son nom soient affichés.', verbose_name='Accord écrit du client')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['sort_order', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_published', False), ('consent_given', True), _connector='OR'), name='testimonial_published_requires_consent')],
            },
        ),
    ]
