# Generated by Django 5.2.17 on 2026-09-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Téléphone / WhatsApp'),
        ),
        migrations.AddField(
            model_name='proposalrequest',
            name='plan',
            field=models.CharField(blank=True, choices=[('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='Formule souhaitée'),
        ),
    ]
