# Generated by Django 5.2.17 on 2026-09-28 09:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_proposal_request_phone_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': 'Cotisation', 'verbose_name_plural': 'Cotisations'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Rencontre', 'verbose_name_plural': 'Rencontres'},
        ),
        migrations.AlterModelOptions(
            name='meetingentry',
            options={'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.AlterModelOptions(
            name='organ',
            options={'verbose_name': 'Organe', 'verbose_name_plural': 'Organes'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Poste', 'verbose_name_plural': 'Postes'},
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('monthly', 'Mensuelle'), ('annual', 'Annuelle'), ('spontaneous', 'Spontanée'), ('late_fine', 'Amende retard'), ('absence_fine', 'Amende absence'), ('other', 'Autre')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Identifiant de transaction'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.member', verbose_name='Membre'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='paid_at',
            field=models.DateField(verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('failed', 'Échouée')], default='confirmed', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=200, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=200, verbose_name="Type d'événement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='group',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_at',
            field=models.DateTimeField(verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='meetingentry',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.meeting', verbose_name='Rencontre'),
        ),
        migrations.AlterField(
            model_name='meetingentry',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_entries', to='core.member', verbose_name='Membre'),
        ),
        migrations.AlterField(
            model_name='meetingentry',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='meetingentry',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le'),
        ),
        migrations.AlterField(
            model_name='meetingentry',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('permission', 'Permission')], max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.group', verbose_name='Groupes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='core.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='position',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='position',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.member', verbose_name='Titulaire'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='position',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organ', verbose_name='Organe'),
        ),
    ]
