# Generated by Django 5.2.17 on 2026-09-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_french_field_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='gateway_reference',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='payer_phone',
        ),
    ]
