# Generated by Django 5.2.17 on 2026-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_paygate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dues_start',
            field=models.DateField(blank=True, help_text='Premier mois dû. Vide = date de création du groupe.', null=True, verbose_name='Début des cotisations'),
        ),
        migrations.AddField(
            model_name='group',
            name='monthly_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant que chaque membre doit verser par mois. Vide = pas de suivi des retards.', max_digits=10, null=True, verbose_name='Cotisation mensuelle attendue'),
        ),
    ]
