from django.urls import path

from . import web_views

urlpatterns = [
    path("", web_views.home, name="home"),
    path("entreprise/", web_views.company_page, name="company_page"),
    path("plateforme/", web_views.platform_page, name="platform_page"),
    path("devis/", web_views.proposal_page, name="proposal_page"),
    path("admin-workspace/", web_views.AdminWorkspaceView.as_view(), name="admin_workspace"),
    path("manager-workspace/", web_views.ManagerWorkspaceView.as_view(), name="manager_workspace"),
    path("recherche/", web_views.GlobalSearchView.as_view(), name="global_search"),
    path("groupes/", web_views.GroupListView.as_view(), name="group_list"),
    path("groupes/<int:pk>/dashboard/", web_views.GroupDashboardView.as_view(), name="group_dashboard"),
    path("groupes/nouveau/", web_views.GroupCreateView.as_view(), name="group_create"),
    path("groupes/<int:pk>/modifier/", web_views.GroupUpdateView.as_view(), name="group_update"),
    path("groupes/<int:pk>/supprimer/", web_views.GroupDeleteView.as_view(), name="group_delete"),
    path("organes/", web_views.OrganListView.as_view(), name="organ_list"),
    path("organes/nouveau/", web_views.OrganCreateView.as_view(), name="organ_create"),
    path("organes/<int:pk>/modifier/", web_views.OrganUpdateView.as_view(), name="organ_update"),
    path("organes/<int:pk>/supprimer/", web_views.OrganDeleteView.as_view(), name="organ_delete"),
    path("membres/", web_views.MemberListView.as_view(), name="member_list"),
    path("membres/nouveau/", web_views.MemberCreateView.as_view(), name="member_create"),
    path("membres/<int:pk>/modifier/", web_views.MemberUpdateView.as_view(), name="member_update"),
    path("membres/<int:pk>/supprimer/", web_views.MemberDeleteView.as_view(), name="member_delete"),
    path("postes/", web_views.PositionListView.as_view(), name="position_list"),
    path("postes/nouveau/", web_views.PositionCreateView.as_view(), name="position_create"),
    path("postes/<int:pk>/modifier/", web_views.PositionUpdateView.as_view(), name="position_update"),
    path("postes/<int:pk>/supprimer/", web_views.PositionDeleteView.as_view(), name="position_delete"),
    path("rencontres/", web_views.MeetingListView.as_view(), name="meeting_list"),
    path("rencontres/nouveau/", web_views.MeetingCreateView.as_view(), name="meeting_create"),
    path("rencontres/<int:pk>/modifier/", web_views.MeetingUpdateView.as_view(), name="meeting_update"),
    path("rencontres/<int:pk>/supprimer/", web_views.MeetingDeleteView.as_view(), name="meeting_delete"),
    path("presences/", web_views.MeetingEntryListView.as_view(), name="meeting_entry_list"),
    path("presences/nouveau/", web_views.MeetingEntryCreateView.as_view(), name="meeting_entry_create"),
    path("presences/<int:pk>/modifier/", web_views.MeetingEntryUpdateView.as_view(), name="meeting_entry_update"),
    path("presences/<int:pk>/supprimer/", web_views.MeetingEntryDeleteView.as_view(), name="meeting_entry_delete"),
    path("presences/export/csv/", web_views.export_meeting_entries_csv, name="meeting_entry_export_csv"),
    path("presences/export/xlsx/", web_views.export_meeting_entries_xlsx, name="meeting_entry_export_xlsx"),
    path("presences/export/pdf/", web_views.export_meeting_entries_pdf, name="meeting_entry_export_pdf"),
    path("cotisations/", web_views.ContributionListView.as_view(), name="contribution_list"),
    path("cotisations/nouveau/", web_views.ContributionCreateView.as_view(), name="contribution_create"),
    path("cotisations/<int:pk>/modifier/", web_views.ContributionUpdateView.as_view(), name="contribution_update"),
    path("cotisations/<int:pk>/supprimer/", web_views.ContributionDeleteView.as_view(), name="contribution_delete"),
    path("cotisations/export/csv/", web_views.export_contributions_csv, name="contribution_export_csv"),
    path("cotisations/export/xlsx/", web_views.export_contributions_xlsx, name="contribution_export_xlsx"),
    path("cotisations/export/pdf/", web_views.export_contributions_pdf, name="contribution_export_pdf"),
    path("documents/", web_views.DocumentListView.as_view(), name="document_list"),
    path("documents/nouveau/", web_views.DocumentCreateView.as_view(), name="document_create"),
    path("documents/<int:pk>/modifier/", web_views.DocumentUpdateView.as_view(), name="document_update"),
    path("documents/<int:pk>/supprimer/", web_views.DocumentDeleteView.as_view(), name="document_delete"),
    path("evenements/", web_views.EventListView.as_view(), name="event_list"),
    path("evenements/nouveau/", web_views.EventCreateView.as_view(), name="event_create"),
    path("evenements/<int:pk>/modifier/", web_views.EventUpdateView.as_view(), name="event_update"),
    path("evenements/<int:pk>/supprimer/", web_views.EventDeleteView.as_view(), name="event_delete"),
    path("audit-logs/", web_views.AuditLogListView.as_view(), name="audit_log_list"),
]
